= maven-formula

https://travis-ci.com/saltstack-formulas/maven-formula[image:https://travis-ci.com/saltstack-formulas/maven-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Formula to install Apache Maven on GNU/Linux and MacOS.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

If you need (non-default) configuration, please pay attention to the
`pillar.example` file and/or link:#_special_notes[Special notes] section.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Special notes

None.

== Available states

=== `maven`

_Meta-state (This is a state that includes other states)_.

This installs Maven package, manages Maven configuration file and then
configures the development environment.

=== `maven.archive`

This state will install Maven from archive only.

=== `maven.package`

This state will install Maven homebrew package on MacOS.

=== `maven.config`

This state will configure npmrc and/or environment and has a dependency
on `maven.install` via include list.

=== `maven.linuxenv`

This state will install some Maven linux-alternatives on GNU/Linux.

=== `maven.clean`

_Meta-state (This is a state that includes other states)_.

this state will undo everything performed in the `maven` meta-state in
reverse order, i.e. removes the configuration file and then uninstalls
the package.

=== `maven.config.clean`

This state will remove the configuration of Maven and has a dependency
on `maven.package.clean` via include list.

=== `maven.archive.clean`

This state will remove Maven package and has a dependency on
`maven.config.clean` via include list.

=== `maven.package.clean`

This state will remove Maven package on MacOS, and has dependency on
`maven.config.clean` via include list.

=== `maven.linuxenv.clean`

This state will remove Maven linux-alternatives on GNU/Linux.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `maven` main state, ready for
testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
